spring:
  application:
    name: Get_a_Job
  datasource:
    url: jdbc:h2:./db/test;AUTO_SERVER=TRUE;NON_KEYWORDS=VALUE
    username: root
    password: 1234
    driver-class-name: org.h2.Driver


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  liquibase:
    change-log: classpath:/db/changelog/master.yaml

  mail:
    host: smtp.gmail.com
    port: 587
    username: tzolcubekov@gmail.com
    password: cddmjjrqjxmchijd
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
#        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# Logging
logging:
  level:
    root: INFO
    springboot.get_a_job: DEBUG
  file:
    path: log

upload:
  path: "./data/images/"





